export const OrderStatus = {
  DRAFT: 'DRAFT',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_AUTHORIZED: 'PAYMENT_AUTHORIZED',
  PROCUREMENT_PENDING: 'PROCUREMENT_PENDING',
  PROCUREMENT_REVIEW: 'PROCUREMENT_REVIEW',
  PROCUREMENT_APPROVED: 'PROCUREMENT_APPROVED',
  PROCUREMENT_STARTED: 'PROCUREMENT_STARTED',
  PROCUREMENT_CONFIRMED: 'PROCUREMENT_CONFIRMED',
  SUPPLIER_OUT_OF_STOCK: 'SUPPLIER_OUT_OF_STOCK',
  SUPPLIER_PRICE_CHANGED: 'SUPPLIER_PRICE_CHANGED',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  FULFILLMENT_PENDING: 'FULFILLMENT_PENDING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  RETURN_REQUESTED: 'RETURN_REQUESTED',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUNDED: 'REFUNDED',
  FAILED: 'FAILED',
} as const;

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];
